#! /bin/sh

wallpaper=/home/kmrn/usr/img/walls/black.jpg

sxhkd &
xsetroot -cursor_name left_ptr


if [[ "$(hostname -s)" == 'cmptr' ]]; then
    bspc monitor "DVI-D-0" -d I II III IV V VI VII VIII IX X
elif [[ "$(hostname -s)" == 'lvcmptr' ]]; then
    bspc monitor "eDP-1" -d I II III IV V VI VII VIII IX X
else
    echo "Fix your dots"
fi


bspc config border_width         	2
bspc config window_gap          	14
bspc config active_border_color \#191919
bspc config normal_border_color \#6f6f6f
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true
bspc config border_radius        10

bspc rule -a Firefox desktop='^2'
bspc rule -a Nightly desktop='^2'
bspc rule -a 'jetbrains-idea-ce' desktop='^3'
bspc rule -a Chromium='^4'
bspc rule -a Zathura state=tiled desktop='^5'
bspc rule -a Steam state=tiled desktop='^6'
bspc rule -a 'Google Play Music Desktop Player' desktop='^10'
bspc rule -a 'Spotify' desktop='^10'

# Autostart
urxvtd -q -f -o &
/home/kmrn/.screenlayout/main.sh ;

compton -b &
feh --bg-fill $wallpaper &
dunst &
$HOME/.config/dunst/gpmdp.sh &
xrdb /home/kmrn/.Xresources ;

firefox &
chromium & 
polybar -r cmptr &
blurwal -s 15 &
#/home/kmrn/bin/blurme/blurme &
# idea.sh &
#/home/kmrn/.config/bspc/launchBars *
#/home/kmrn/.config/bspwm/launchWorkspace.sh &
unclutter &
spotify
