#! /bin/sh

wallpaper=/home/kmrn/usr/img/walls/black.jpg

sxhkd &
xsetroot -cursor_name left_ptr

bspc monitor DVI-D-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         	2
bspc config window_gap          	14
bspc config active_border_color \#191919
bspc config normal_border_color \#6f6f6f
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true

bspc rule -a Firefox desktop='^2'
bspc rule -a Nightly desktop='^2'
bspc rule -a 'jetbrains-idea-ce' desktop='^3'
bspc rule -a 'Google Play Music Desktop Player' desktop='^10'
bspc rule -a Zathura state=tiled
bspc rule -a Steam state=tiled desktop='^9'

# Autostart
feh --bg-fill $wallpaper &
compton -b &
dunst &
xrdb /home/kmrn/.Xresources ;

polybar cmptr &
/home/kmrn/.config/bspwm/launchWorkspace.sh ;
firefox &
idea.sh &
