#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	2
bspc config window_gap          	12
bspc config normal_border_color \#cc5c8c6
bspc config active_border_color \#c000000

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
feh --bg-fill /home/kmrn/usr/img/mtns.jpg &
compton &
tint2 -c /home/kmrn/etc/tint2/hzlrg &
xrdb /home/kmrn/.Xresources ;
urxvt & urxvt & urxvt &
