#  _____ _____ _____ _____ _____
# |__   |   __|   | | __  |  |  |
# |   __|   __| | | | __ -|  |  |
# |_____|_____|_|___|_____|_____|

# by: khazelrigg

name: " "

colors:
    
    background: ""
    foreground: ""
    
    black:
        normal: ""
        bold:   ""
    red:
        normal: ""
        bold:   ""
    green:
        normal: ""
        bold:   ""
    yellow:
        normal: ""
        bold:   ""
    blue:
        normal: ""
        bold:   ""
    magenta:
        normal: ""
        bold:   ""
    cyan:
        normal: ""
        bold:   ""
    white:
        normal: ""
        bold:   ""

neovim:
        colorscheme: ""

wal: ""
